{% set version = "0.10.1" %}

package:
    name: pyfftw
    version: {{ version }}

source:
    fn: pyFFTW-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-{{ version }}.tar.gz
    md5: dab57de9d23f3b333115265914f3d240
    patches:
        # incorporate static build capability from pyFFTW/pyFFTW#116
        - setup.patch

build:
  number: 0
  skip: True  # [win]

requirements:
    build:
        - cython
        - python
        - mkl    11.3.3  0
        - numpy  x.x
        - numpy  1.10.4  py27_2  # [py27 and np==110]
        - numpy  1.11.0  py27_1  # [py27 and np==111]
        - numpy  1.11.0  py27_1  # [py27 and np==111]
        - numpy  1.10.4  py34_2  # [py34 and np==110]
        - numpy  1.11.0  py34_1  # [py34 and np==111]
        - numpy  1.10.4  py35_2  # [py35 and np==110]
        - numpy  1.11.0  py35_1  # [py35 and np==111]
        - fftw
    run:
        - python
        - mkl    11.3.3  0
        - numpy  x.x
        - numpy  1.10.4  py27_2  # [py27 and np==110]
        - numpy  1.11.0  py27_1  # [py27 and np==111]
        - numpy  1.11.0  py27_1  # [py27 and np==111]
        - numpy  1.10.4  py34_2  # [py34 and np==110]
        - numpy  1.11.0  py34_1  # [py34 and np==111]
        - numpy  1.10.4  py35_2  # [py35 and np==110]
        - numpy  1.11.0  py35_1  # [py35 and np==111]

test:
    requires:
        - mkl    11.3.3  0
        - numpy  1.10.4  py27_2  # [py27 and np==110]
        - numpy  1.11.0  py27_1  # [py27 and np==111]
        - numpy  1.11.0  py27_1  # [py27 and np==111]
        - numpy  1.10.4  py34_2  # [py34 and np==110]
        - numpy  1.11.0  py34_1  # [py34 and np==111]
        - numpy  1.10.4  py35_2  # [py35 and np==110]
        - numpy  1.11.0  py35_1  # [py35 and np==111]
        - fftw   3.3.4   3

    imports:
        - pyfftw
        - pyfftw.builders
        - pyfftw.interfaces

about:
    home: http://hgomersall.github.com/pyFFTW/
    license: BSD or GPL 2
    summary: 'A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.'

extra:
    recipe-maintainers:
        - grlee77
        - jakirkham
        - jjhelmus
